[package]
name = "supermodel"
description = "Supermodel is an abstract data-modeling library."
license-file = "../../LICENSE"
repository = "https://github.com/peterhenryd/supermodel"
readme = "../../README.md"
keywords = ["sql", "sqlx", "mysql", "postgres", "sqlite"]
categories = ["data-structures", "database"]
version = "0.1.0"
edition = "2021"

[features]
macros = ["supermodel-macros"]

[dependencies]
supermodel-macros = { path = "../supermodel-macros", version = "0.1.0", optional = true }

[dev-dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
supermodel-sqlx = { path = "../supermodel-sqlx", features = ["postgres", "runtime-tokio", "tls-rustls"] }
supermodel = { path = "../supermodel", features = ["macros"] }